name: "regex-parse"
description: "Match and parse an input string against a given regex pattern."
inputs:
  pattern:
    description: "regex pattern"
    required: true
  input:
    description: "input string to match and parse"
    required: true
outputs: {}
runs:
  using: "node16"
  main: "dist/index.js"
