name: Test
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
  apply:
    runs-on: ubuntu-latest
    env:
      i: j
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: my_step
        # test includes
        # - reference of previous static and computed results
        # - preservation of input ordering
        # - multiline string and double and trailing whitespace
        # - quoting inside and outside of substitutions
        # - subshell use
        with:
          x: "env.i=${{env.i}}"
          z: "according to x, ${x}"
          y: |
            ${z}.  That is, $(echo "${x}"). 
            Meaning that 'env.i' is indeed "$(echo "${{env.i}}")".
      - run: |
          [ "${{steps.my_step.outputs.x}}" = "env.i=j" ]
          [ "${{steps.my_step.outputs.z}}" = "according to x, env.i=j" ]
          [ "${{steps.my_step.outputs.y}}" = "according to x, env.i=j.  That is, env.i=j. 
          Meaning that 'env.i' is indeed "j".
          " ]
    # TODO Add check that failure breaks the workflow.
